apiVersion: v1
kind: Service
metadata:
  name: owner-service
  namespace: yelp-app
spec:
  selector:
    app: owner
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  type: ClusterIP