apiVersion: v1
kind: Secret
metadata:
  name: yelp-secret
  namespace: yelp-app
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASSWORD: "seekrit"
  SECRET_KEY: "change-this-to-a-long-random-secret"
  TAVILY_API_KEY: "dummy-key"