apiVersion: v1
kind: Service
metadata:
  name: user-reviewer-service
  namespace: yelp-app
spec:
  selector:
    app: user-reviewer
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP