FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
WORKDIR /app/app
EXPOSE 8001

CMD ["uvicorn", "user_reviewer_service_main:app", "--host", "0.0.0.0", "--port", "8001"]